### PR TITLE
Adjust to passing in machines/users include flag.

### PR DESCRIPTION
**Pull request by anastasiamac**
## Description of change

Mostly tests and interfaces adjustments for getting a new flag passed in.

Questions:
* I am not too keen on having user as an Entity in new params structure. Why not names.UserTag?
* At the apiserver layer, we just want to translate machines and users if we get them from state. Right?
* If we are not requesting machines' details, we will get a model machines and cores count. Correct?

### CODE REVIEW

**Comment by jameinel** [comment]
Just responding to the summary.

Entity: I was just using what was obvious from other API calls. We
certainly don't need to take a machine agent, so if it is easier to switch
to UserTag that's fine. But I'm not sure that UserTag gets
created/serialized correctly on the wire.

I did change it to always expose the machine count. I actually wonder if we
should just put it in there always. Consider, if you can run 'juju status'
and see the info, why would we hide it from 'juju models' ?

apiserver sounds like  good place to translate state objects into API ones.

John
=:->


On Nov 22, 2017 06:27, "anastasiamac" <notifications@github.com> wrote:

Description of change

Mostly tests and interfaces adjustments for getting a new flag passed in.

Questions:

   - I am not too keen on having user as an Entity in new params structure.
   Why not names.UserTag?
   - At the apiserver layer, we just want to translate machines and users
   if we get them from state. Right?
   - If we are not requesting machines' details, we will get a count.
   Correct?

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/jameinel/juju/pull/11
Commit Summary

   - Adjust to getting machines/users include flag.

File Changes

   - *M* api/modelmanager/modelmanager.go
   <https://github.com/jameinel/juju/pull/11/files#diff-0> (11)
   - *M* api/modelmanager/modelmanager_test.go
   <https://github.com/jameinel/juju/pull/11/files#diff-1> (18)
   - *M* apiserver/facades/client/modelmanager/listmodelsinfo_test.go
   <https://github.com/jameinel/juju/pull/11/files#diff-2> (66)
   - *M* apiserver/facades/client/modelmanager/modelinfo_test.go
   <https://github.com/jameinel/juju/pull/11/files#diff-3> (4)
   - *M* apiserver/facades/client/modelmanager/modelmanager.go
   <https://github.com/jameinel/juju/pull/11/files#diff-4> (67)
   - *M* cmd/juju/controller/listmodels.go
   <https://github.com/jameinel/juju/pull/11/files#diff-5> (6)
   - *M* cmd/juju/controller/listmodels_test.go
   <https://github.com/jameinel/juju/pull/11/files#diff-6> (4)
   - *M* state/modeluser.go
   <https://github.com/jameinel/juju/pull/11/files#diff-7> (2)

Patch Links:

   - https://github.com/jameinel/juju/pull/11.patch
   - https://github.com/jameinel/juju/pull/11.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jameinel/juju/pull/11>, or mute the thread

**Comment by anastasiamac** [comment]
1. I'll change to UserTag
2. Once we merge this, I  am happy to clean up currrent apiserver layer to do just that.
3. In any format, if we have machine info, we only display cores not anything else... even though we theoritically get all machine details... I wonder if it's worthwhile preserving tabular format as is - display machine counts and total cores, but change yaml and json to display full machine details per machine. It includes some interesting info like availability zones, etc...

**Comment by jameinel** [comment]
On Nov 22, 2017 06:42, "anastasiamac" <notifications@github.com> wrote:


   1. I'll change to UserTag
   2. Once we merge this, I am happy to clean up currrent apiserver layer
   to do just that.
   3. In any format, if we have machine info, we only display cores not
   anything else... even though we theoritically get all machine details... I
   wonder if it's worthwhile preserving tabular format as is - display machine
   counts and total cores, but change yaml and json to display full machine
   details per machine. It includes some interesting info like availability
   zones, etc...

I tested 2.2.6 and it displays full info in YAML format. which we should
preserve.



—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jameinel/juju/pull/11#issuecomment-346226527>, or mute
the thread

**Comment by jameinel** [comment]
There is certainly an argument to be had that list-models is not the place
to get full details. Instead that should be optional at most or show-model
instead. But at this point I don't feel like it's worth breaking
compatibility.
John
=:->

On Nov 22, 2017 06:44, "John Meinel" <john@arbash-meinel.com> wrote:



On Nov 22, 2017 06:42, "anastasiamac" <notifications@github.com> wrote:


   1. I'll change to UserTag
   2. Once we merge this, I am happy to clean up currrent apiserver layer
   to do just that.
   3. In any format, if we have machine info, we only display cores not
   anything else... even though we theoritically get all machine details... I
   wonder if it's worthwhile preserving tabular format as is - display machine
   counts and total cores, but change yaml and json to display full machine
   details per machine. It includes some interesting info like availability
   zones, etc...

I tested 2.2.6 and it displays full info in YAML format. which we should
preserve.



—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jameinel/juju/pull/11#issuecomment-346226527>, or mute
the thread

**Comment by anastasiamac** [comment]
I appreciate you looking and testing 2.2.6.

However, according to the code and the results, I am certain that we only *display* cores. It does not mean that we do not send everything under the sun form the api, it means that we ignore it all and only display cores :D 

code: https://github.com/jameinel/juju/blob/2.3-direct-models-1732384/cmd/juju/common/model.go#L45
unit test results: http://pastebin.ubuntu.com/26016886/

**Comment by anastasiamac** [comment]
Looking at all other params structures, we could keep user as a params.Entity (there is definetely precedence for that). Newer implementations seem to be heavily skewed towards tags as a string and enforce parse-ability :)

**Comment by jameinel** [comment]
Talking with the tech board, they were +1 on removing the details of
machines and users from 'list-models' entirely. As long as you can get that
information from "show-model".

**Pull request merged**
